### ISSUE TITLE
Target 1.0.0 embedded hal interface

### ISSUE THREAD

**Issue by nathaniel-brough** [silvergasp/embedded-hal-fuzz#10]
We should begin supporting this and use a compatibility layer to support old versions.

**Comment by nathaniel-brough** [comment]
**TODO:**
- [x]  Implement 1.0.0-alpha.8 traits
- [ ]  Add compatibility layer for previous stable (i.e. "0.2.7") traits. Tracking issue: ryankurte/embedded-hal-compat#9
- [ ]  Create configurable selection feature for compatibility layer.
